name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Executa toda vez que você atualizar a branch main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Mover Frontend para a Raiz de Publicação
        run: |
          mkdir temporario
          cp -r frontend/public/* temporario/
          # Se houver um index.html na raiz que redireciona, ou se o home.html deve ser o index:
          cp temporario/pages/home.html temporario/index.html || true

      - name: Deploy no GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: temporario # Publica apenas o conteúdo da pasta pública
          branch: gh-pages # Envia para esta branch isolada
